[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ollama-crewai"
version = "0.1.0"
dependencies = [
    "requests>=2.31.0",
]

[project.scripts]
ollama-crewai = "main:main"

[tool.setuptools]
py-modules = ["main"]
package-dir = {"" = "src"}
