objective: "Plan. Implement. Test."
agents:
  planner:
    model: llama3
    tools: []
  developer:
    model: codellama
    tools: [filesystem]
  writer:
    model: llama3
    tools: [filesystem]
  tester:
    model: llama3
    tools: [pytest]
  researcher:
    model: mistral
    tools: [aiohttp]
