objective: "Créer un site web simple présentant les stratégies d'entraînement en trail (course à pied, trail, renforcement, yoga, etc.) et fournir une critique de chaque étape."
policies:
  allowed_commands: [plan, code, write, test, research]
  network_access: false
storage:
  path: state.json
supervision:
  enabled: true
agents:
  planner:
    model: llama3
    tools: []
  developer:
    model: codellama
    tools: [filesystem]
  writer:
    model: llama3
    tools: [filesystem]
  tester:
    model: llama3
    tools: [pytest]
  researcher:
    model: mistral
    tools: [aiohttp]
